-- PARITY TEST: autopricing_ab_test (dbt model SQL) vs legacy analysis.autopricing_ab_test
-- Generated by /migrate-table. Zero rows returned = pass. Any row returned =
-- the test FAILS and the row tells you which day broke and on which metric.
--
-- The NEW side is the model's own SQL inlined below as the `model_output` CTE,
-- NOT a ref() to a built table: no table has to exist (or be paid for) before
-- this gate runs. Each test run recomputes the model over the window (~one
-- fixed upstream scan, ~$4 for this model).
--
-- Window    : last 2 COMPLETE days  (created_at >= current_date - 2 and < current_date)
-- Tolerance : 1% relative on every metric (var 'tolerance', default 0.01).
--             Historical days recomputed from today's sources see late-arriving
--             data the legacy snapshot froze out (pilot: ~+0.3% rows, new side
--             higher). Same-day-computed days should match exactly.
--
--   uv run dbt test --select parity__autopricing_ab_test --profiles-dir .
--   uv run dbt test --select parity__autopricing_ab_test --vars '{tolerance: 0.0001}' --profiles-dir .   # strict
--
-- Fingerprints (grain = created_at):
--   row_count                     count(*)
--   distinct_fares                count(distinct fare_id)              fan-out from the session join
--   distinct_searches             count(distinct search_id)            main join key
--   distinct_sessions             count(distinct session_id)           join-produced key
--   original_fare_usd_sum         round(sum(bow_original_total_fare_usd), 2)
--   final_fare_usd_sum            round(sum(bow_final_total_fare_usd), 2)
--   final_margin_usd_sum          round(sum(bow_final_net_margin_usd), 2)
--   clicks_sum                    sum(click)
--   rows_with_variant             countif(variant is not null)         LEFT JOIN coverage
--   distinct_pos                  count(distinct site_code)
--   distinct_routes               count(distinct airport_route_revised) top-60% route filter
--   distinct_airlines             count(distinct first_airline)
--
-- Skipped columns (not fingerprinted):
--   other dates      : created_at_timestamp, departure_date, arrival_date
--   free text        : *_name columns, designator_codes, fare_count_concat, trip_fare_agg,
--                      trip_legs, trip_segments, trip_airport_codes, trip_airport_names,
--                      trip_city_codes, trip_city_names, trip_country_codes, trip_country_names,
--                      trip_airline_codes, trip_airline_names, trip_depature_times,
--                      trip_arrival_times, trip_cabin_names, trip_designator_codes,
--                      trip_timings, trip_dates
--   filter constants : provider_code, providers_status, trip_type, first_stop_count
--   local-currency   : fare_amount_local_currency, fare_currency_code,
--                      bow_original_total_local_currency, bow_local_currency
--   margin parts     : bow_gds/iata/plb_commission_usd, bow_payment_gateway_fee_usd,
--                      bow_vendor_fee_usd, bow_original_net_margin(_usd/_percentage),
--                      bow_final_net_margin, bow_final_net_margin_percentage,
--                      bow_markup(_usd/_percentage), bow_min/max_margin_percentage,
--                      bow_original_fare_usd, bow_final_fare_usd
--   other            : trip_id, experiment, fare_amount_usd, rank, wego_top_10,
--                      wego_not_top_10, provider_type, trip_category, trip_duration,
--                      adults/children/infants/total_pax_count, conversions_tracked,
--                      trip_min_fare_amount_usd(_exclude_own_fare),
--                      trip_if_cheapest_provider_code, trip_provider_code_count,
--                      trip_cheapest_provider_code_count, fare_parity_pct,
--                      cheapest/clicked/converted_provider, price/click/conversion_win,
--                      bow_fare_ipcc, bow_booking_ipcc, bow_validating_airline_code,
--                      bow_vendor_commission_rbd, bow_booking_margin_id,
--                      bow_booking_margin_rbd, bow_action, country_route, city_route,
--                      airport_route, first_*_code columns

{% set tol = var('tolerance', 0.01) %}

with model_output as (
    -- ===== models/autopricing_ab_test.sql, verbatim minus config(); the
    -- ===== run_date predicate is replaced by the comparison window below.
    with sessions as (
        select date(created_at) as created_at_date, session_id, variant, experiment
        from {{ source('wego_analytics', 'ab_testing') }}
        where timestamp_trunc(created_at, day) >= timestamp("2026-06-01")
        group by 1, 2, 3, 4
    ),

    searches as (
        -- original used select *; only these two columns are used downstream,
        -- and BigQuery bills per column read
        select session_id, search_id
        from {{ source('wego_analytics', 'flights_searches') }}
        where timestamp_trunc(_PARTITIONTIME, day) >= timestamp("2026-06-01")
    ),

    searches_experiment as (
        select a.*, b.search_id
        from sessions as a
        left join searches as b on a.session_id = b.session_id
    ),

    base_table as (
        select
            a.*,
            concat(first_departure_airport_code, "-", first_arrival_airport_code) as airport_route_revised,
            b.variant, b.experiment, b.session_id
        from {{ source('analysis', 'pricing_fares_analysis') }} as a
        left join searches_experiment as b
            on a.search_id = b.search_id
        -- comparison window (replaces the model's run_date predicate)
        where a.created_at >= date_sub(current_date, interval 2 day)
          and a.created_at <  current_date
          and a.provider_code = 'wego.com'
          and a.providers_status = 'multiple providers'
          and a.trip_type = 'oneway'
          and a.first_stop_count = 0
          and a.bow_original_total_fare_usd is not null
    ),

    dim as (
        select
            concat(flights_pricing_fares_analysis_v2.first_departure_airport_code, "-", flights_pricing_fares_analysis_v2.first_arrival_airport_code) as airport_route,
            flights_pricing_fares_analysis_v2.first_airline as airline,
            flights_pricing_fares_analysis_v2.site_code as site_code,
            coalesce(sum(flights_pricing_fares_analysis_v2.click), 0) as total_clicks,
            sum(coalesce(sum(flights_pricing_fares_analysis_v2.click), 0)) over (order by coalesce(sum(flights_pricing_fares_analysis_v2.click), 0) desc) as cum_sum,
            sum(coalesce(sum(flights_pricing_fares_analysis_v2.click), 0)) over () as total
        from {{ source('analysis', 'pricing_fares_analysis') }} as flights_pricing_fares_analysis_v2
        where flights_pricing_fares_analysis_v2.created_at >= date('2026-01-01')
          and flights_pricing_fares_analysis_v2.created_at < date('2026-06-30')
          and provider_code = 'wego.com'
          and providers_status = 'multiple providers'
          and trip_type = 'oneway'
          and first_stop_count = 0
          and bow_original_total_fare_usd is not null
        group by 1, 2, 3
        order by 4 desc
    )

    select a.*
    from base_table as a
    inner join (select * from dim where cum_sum / total <= 0.60) as b
        on a.airport_route_revised = b.airport_route
        and a.first_airline = b.airline
        and a.site_code = b.site_code
    -- ===== end of model SQL
),

new_side as (
    select
        created_at,
        count(*)                                        as row_count,
        count(distinct fare_id)                         as distinct_fares,
        count(distinct search_id)                       as distinct_searches,
        count(distinct session_id)                      as distinct_sessions,
        round(sum(bow_original_total_fare_usd), 2)      as original_fare_usd_sum,
        round(sum(bow_final_total_fare_usd), 2)         as final_fare_usd_sum,
        round(sum(bow_final_net_margin_usd), 2)         as final_margin_usd_sum,
        sum(click)                                      as clicks_sum,
        countif(variant is not null)                    as rows_with_variant,
        count(distinct site_code)                       as distinct_pos,
        count(distinct airport_route_revised)           as distinct_routes,
        count(distinct first_airline)                   as distinct_airlines
    from model_output
    group by 1
),

legacy_side as (
    select
        created_at,
        count(*)                                        as row_count,
        count(distinct fare_id)                         as distinct_fares,
        count(distinct search_id)                       as distinct_searches,
        count(distinct session_id)                      as distinct_sessions,
        round(sum(bow_original_total_fare_usd), 2)      as original_fare_usd_sum,
        round(sum(bow_final_total_fare_usd), 2)         as final_fare_usd_sum,
        round(sum(bow_final_net_margin_usd), 2)         as final_margin_usd_sum,
        sum(click)                                      as clicks_sum,
        countif(variant is not null)                    as rows_with_variant,
        count(distinct site_code)                       as distinct_pos,
        count(distinct airport_route_revised)           as distinct_routes,
        count(distinct first_airline)                   as distinct_airlines
    from {{ source('analysis', 'autopricing_ab_test_legacy') }}
    where created_at >= date_sub(current_date, interval 2 day)
      and created_at <  current_date
    group by 1
)

select
    coalesce(n.created_at, l.created_at) as day,
    case
        when n.created_at is null then 'day missing in dbt model'
        when l.created_at is null then 'day missing in legacy table'
        when abs(n.row_count - l.row_count) / nullif(abs(l.row_count), 0) > {{ tol }} then 'row count mismatch'
        when abs(n.distinct_fares - l.distinct_fares) / nullif(abs(l.distinct_fares), 0) > {{ tol }} then 'distinct fares mismatch'
        when abs(n.distinct_searches - l.distinct_searches) / nullif(abs(l.distinct_searches), 0) > {{ tol }} then 'distinct searches mismatch'
        when abs(n.distinct_sessions - l.distinct_sessions) / nullif(abs(l.distinct_sessions), 0) > {{ tol }} then 'distinct sessions mismatch'
        when abs(n.original_fare_usd_sum - l.original_fare_usd_sum) / nullif(abs(l.original_fare_usd_sum), 0) > {{ tol }} then 'original fare sum mismatch'
        when abs(n.final_fare_usd_sum - l.final_fare_usd_sum) / nullif(abs(l.final_fare_usd_sum), 0) > {{ tol }} then 'final fare sum mismatch'
        when abs(n.final_margin_usd_sum - l.final_margin_usd_sum) / nullif(abs(l.final_margin_usd_sum), 0) > {{ tol }} then 'final margin sum mismatch'
        when abs(n.clicks_sum - l.clicks_sum) / nullif(abs(l.clicks_sum), 0) > {{ tol }} then 'clicks sum mismatch'
        when abs(n.rows_with_variant - l.rows_with_variant) / nullif(abs(l.rows_with_variant), 0) > {{ tol }} then 'variant coverage mismatch'
        when abs(n.distinct_pos - l.distinct_pos) / nullif(abs(l.distinct_pos), 0) > {{ tol }} then 'distinct POS mismatch'
        when abs(n.distinct_routes - l.distinct_routes) / nullif(abs(l.distinct_routes), 0) > {{ tol }} then 'distinct routes mismatch'
        when abs(n.distinct_airlines - l.distinct_airlines) / nullif(abs(l.distinct_airlines), 0) > {{ tol }} then 'distinct airlines mismatch'
    end as failed_check,
    n.row_count             as new_rows,           l.row_count             as legacy_rows,
    n.distinct_fares        as new_fares,          l.distinct_fares        as legacy_fares,
    n.distinct_searches     as new_searches,       l.distinct_searches     as legacy_searches,
    n.distinct_sessions     as new_sessions,       l.distinct_sessions     as legacy_sessions,
    n.original_fare_usd_sum as new_original_fare,  l.original_fare_usd_sum as legacy_original_fare,
    n.final_fare_usd_sum    as new_final_fare,     l.final_fare_usd_sum    as legacy_final_fare,
    n.final_margin_usd_sum  as new_final_margin,   l.final_margin_usd_sum  as legacy_final_margin,
    n.clicks_sum            as new_clicks,         l.clicks_sum            as legacy_clicks,
    n.rows_with_variant     as new_with_variant,   l.rows_with_variant     as legacy_with_variant,
    n.distinct_pos          as new_pos,            l.distinct_pos          as legacy_pos,
    n.distinct_routes       as new_routes,         l.distinct_routes       as legacy_routes,
    n.distinct_airlines     as new_airlines,       l.distinct_airlines     as legacy_airlines
from new_side n
full outer join legacy_side l using (created_at)
where n.created_at is null
   or l.created_at is null
   or abs(n.row_count - l.row_count) / nullif(abs(l.row_count), 0) > {{ tol }}
   or abs(n.distinct_fares - l.distinct_fares) / nullif(abs(l.distinct_fares), 0) > {{ tol }}
   or abs(n.distinct_searches - l.distinct_searches) / nullif(abs(l.distinct_searches), 0) > {{ tol }}
   or abs(n.distinct_sessions - l.distinct_sessions) / nullif(abs(l.distinct_sessions), 0) > {{ tol }}
   or abs(n.original_fare_usd_sum - l.original_fare_usd_sum) / nullif(abs(l.original_fare_usd_sum), 0) > {{ tol }}
   or abs(n.final_fare_usd_sum - l.final_fare_usd_sum) / nullif(abs(l.final_fare_usd_sum), 0) > {{ tol }}
   or abs(n.final_margin_usd_sum - l.final_margin_usd_sum) / nullif(abs(l.final_margin_usd_sum), 0) > {{ tol }}
   or abs(n.clicks_sum - l.clicks_sum) / nullif(abs(l.clicks_sum), 0) > {{ tol }}
   or abs(n.rows_with_variant - l.rows_with_variant) / nullif(abs(l.rows_with_variant), 0) > {{ tol }}
   or abs(n.distinct_pos - l.distinct_pos) / nullif(abs(l.distinct_pos), 0) > {{ tol }}
   or abs(n.distinct_routes - l.distinct_routes) / nullif(abs(l.distinct_routes), 0) > {{ tol }}
   or abs(n.distinct_airlines - l.distinct_airlines) / nullif(abs(l.distinct_airlines), 0) > {{ tol }}
